server:
  port: 8003

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST:localhost}:${PG_DB_PORT:5432}/${PG_DB_NAME:dip}
    username: ${PG_DB_USERNAME:postgres}
    password: ${PG_DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
