server:
  port: 8002

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST:localhost}:${PG_DB_PORT:5432}/${PG_DB_NAME:dip}
    username: ${PG_DB_USERNAME:postgres}
    password: ${PG_DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

minio:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: ${MINIO_NAME:minioadmin}
  secure: ${MINIO_CERTIFICATION:true}