server:
  port: 8004

spring:
  application:
    name: Email-Kafka-Demo-Project

  mail:
    host: smtp.gmail.com
    port: 587
    username: danlia2000789@gmail.com
    password: Danlia200033
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


