server:
  port: 8004


spring:
  application:
    name: Email-Kafka-Demo-Project


  mail:
    host: smtp.stankin.ru
    port: 587
    username: ait.iist@stankin.ru
    password: Pc82rKt14
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  recipients:
    - danlia2000789@gmail.com
    - danlia2000789@gmail.com
    - danlia2003zx@gmail.com
